### ISSUE TITLE
Implementar un mejor sistema de persistencia en el BOT.

### ISSUE THREAD

**Issue by alexrodriguezlop** [alexrodriguezlop/HDN.PG#58]
Implementar un sistema de persistencia para mejorar la forma en que se almacena la fecha y la hora, que es utilizando un fichero JSOn  a mano.
Este sistema será el encargado de almacenar la fecha y hora de los cifrados y el cual será usado para dar solución a la [HU 4](https://github.com/alexrodriguezlop/HDN.PG/issues/13) usando el Bot para consultar dicha información.

**Comment by JJ** [comment]
Os he dicho repetidas veces que mensajes de commits como el último no sirven de mucho. Y más si se refieren a un issue que ya está cerrado. Prestad un poco de atención a cómo lo hacéis, por favor.
